### ISSUE TITLE
AppodealBanner displays ad but doesn't log impression

### ISSUE THREAD

**Issue by markchen8717** [appodeal/react-native-appodeal#74]
AppodealBanner displays the banner ad fine inside the app, however, the impression is not logged. More over, manually loading an ad and showing it with Appodeal.show(AppodealAdType.BANNER_TOP) will log an impression. I tried to put Appodeal.show(AppodealAdType.BANNER_TOP) inside onAdLoaded but no luck there either.

**Comment by perrosnk** [comment]
I am facing the same issue on Android devices. 
Furthermore, due to the fact that the impression is not logged, the sdk doesn't trigger a banner refresh on Android devices leading to further loss of revenue.
I have filled a bug report to the appodeal team on the website and I am waiting for a response too.

**Comment by Ninjaman494** [comment]
> Furthermore, due to the fact that the impression is not logged, the sdk doesn't trigger a banner refresh on Android devices leading to further loss of revenue.

@perrosnk Were you able to resolve this, and if so how? I'm facing the same issue on with my React Native app on Android. A banner refresh doesn't occur so the same ad is shown across multiple pages.

**Comment by Ninjaman494** [comment]
@staskochkin Was issue closed because it was resolved in an newer release, or is there some other solution? I'm using react-native-appodeal v3.0.1 and still facing the issue described above.
